name: Hatena - Push Published Entries

on:
  pull_request:
    paths:
      - "hatena/entries/**"

jobs:
  push-published-entries:
    uses: hatena/hatenablog-workflows/.github/workflows/push-published-entries.yaml@ce4c0e01255ad9348842e5ce09809c3ec499e43d # v2.0.5
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}