name: Hatena - Pull Draft

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Draft Entry Title"
        required: true

jobs:
  pull-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/pull-draft.yaml@ce4c0e01255ad9348842e5ce09809c3ec499e43d # v2.0.5
    with:
      title: ${{ github.event.inputs.title }}
      draft: true
      BLOG_DOMAIN: ${{ vars.BLOG_DOMAIN }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}