name: Hatena - Push Draft

on:
  pull_request:
    paths:
      - "hatena/draft_entries/**"

jobs:
  push-draft:
    uses: hatena/hatenablog-workflows/.github/workflows/push-draft.yaml@ce4c0e01255ad9348842e5ce09809c3ec499e43d # v2.0.5
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}