name: Hatena - Push Published Entries

on:
  pull_request:
    paths:
      - "hatena/entries/**"
  workflow_call:
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  upload-images:
    if: github.event.pull_request.merged == false
    uses: ./.github/workflows/hatena-upload-images.yaml
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
